### ISSUE TITLE
F-14: Radio Operator Radar range buttons don't work.

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#127]
The buttons to change radar range don't work, those that are in a row on top of the radar.

**Comment by Zaretto** [comment]
related to #126

**Comment by Megaf** [comment]
Not sure if related. Dual control doesn't work in any aircraft in FG.

In this issue I posted, the buttons just don't work in "single player".
Also, the key combo to increase radar range works but the one to decrease radar range doesn't.

**Comment by Zaretto** [comment]
Backseat operations aren't something that I've checked much recently - so I'll try to get time to make it work properly in single player and then fix the MP code.

It could be a general problem with the core; when I investigate the issue I'll see what the problem is and if it's in the core I'll fix it.

If you get chance to raise a ticket on SF for the other aircraft (from FGAddon) that you've found not to work in dual control that would be useful.

**Comment by Megaf** [comment]
> If you get chance to raise a ticket on SF for the other aircraft (from FGAddon) that you've found not to work in dual control that would be useful.

All of them... Me and my friends on Discord tested every single dual control aircraft, none of them work.

> It could be a general problem with the core; when I investigate the issue I'll see what the problem is and if it's in the core I'll fix it.

Thank you for having a look at it!

**Comment by Megaf** [comment]
Fixed, thanks for the good work @NikolaiVChr
