### ISSUE TITLE
F-15/F-14 Performance regression

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#129]
The F-14 used to be one of the lightest aircraft on my system, which I'd get one of the best FPS.

But from many months to know something happen and that's no longer the case, it has been getting worst FPS as commits are made.

**Comment by Zaretto** [comment]
Tested the F-14.

The performance changes appear to be related to the FlightGear core rather than the changes to the F-14.

The current version doesn't run with 2018.3 - so I had to fix these errors first but then I got the following results.
FlightGear started with: 

- --disable-terrasync 
- --fg-root=i:\apps\FlightGear2018.3.5\data
- --fg-scenery=i:/flightgear/scenery
- --fg-scenery=i:/flightgear/custom_scenery
- --terrasync-dir=i:\flightgear\terrasync
- --fg-aircraft=i:/dev/flightgear-models/flightgear/aircraft
- --callsign=Richard
- --multiplay=out,10,mpserver01.flightgear.org,5000
- --multiplay=in,10,,5002
- --httpd=8080
- --prop:/sim/rendering/vsync-enable=false
- --prop:/sim/frame-rate-throttle-hz=30
- --prop:/sim/startup/terminal-ansi-colors=0
- --bpp=32
- --texture-filtering=32
- --prop:/sim/rendering/multi-sample-buffers=1
- --prop:/sim/rendering/multi-samples=4
- --log-level=alert
- --prop:/sim/rendering/osg-notify-level=FATAL
- --prop:/sim/rendering/max-paged-lod=2000
- --prop:/sim/rendering/multithreading-mode=CullThreadPerCameraDrawThreadPerContext

Test case:

- Ascension Island (FHAW)
- RWY 13
- 3nm
- 1200ft
- 200kts. 

Results:

- F-14 V1.8 FlightGear 2020.4 (next) : ~78 fps
- F-14 V2.0 FlightGear 2018.3  : ~117 fps
- F-14 V2.0 FlightGear 2020.4 (nightly): ~60fps

![image](https://user-images.githubusercontent.com/2045654/106743972-5c179200-661f-11eb-8840-d880c90468d6.png)

**Comment by Megaf** [comment]
Maybe related https://sourceforge.net/p/flightgear/codetickets/2532/

**Comment by Megaf** [comment]
It was fixed on recent versions of FG.
