### ISSUE TITLE
F-14: FCS roll. Slow to return to centre.

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#132]
After AFCS improvements the roll channel seems to be ultra slow to return to centre after full left or right stick.

Demosntration
https://www.youtube.com/watch?v=8nXRYBN3a4E

**Comment by Zaretto** [comment]
Thanks for the report.

This made me realise that

1. The moments for pitch and yaw are need to be re-examined
2. Roll FCS only using the outer spoilers (bug)
3. Faults in the FCS where I had used 0.5 instead of 0.05 on roll and yaw

**Comment by Zaretto** [comment]
Please retest - I've made adjustments that I think overall is an airplane that handles better - but more validation is required.

1. Chaange to the FCS so that all spoilers deploy for
   roll control unless DLC active
2. Moments for pitch, roll, yaw corrected because the
   deflection angle, side/set apportionment and
   therefire the coefficients needed to be reworked
   to fix this
3. Fixes to FCS compenstators where 0.5 being used instead
   of 0.05

**Comment by Megaf** [comment]
Ok, the issue I reported is fixed. Roll self centers on stick release as expected.

Now another issue is present. There jitter in the roll, 
Upon moving the stick half way for example, the aircraft starts rolling and stops then starts and stops and so on.

The roll is jittered.

Overall though, it is better.

**Comment by Zaretto** [comment]
The logic has been revised to match the F-14 FCS [1] as documented in NASA-TM-81833 - the fixes are to feed in certain values rather than allowing a jump change.

As far as I can ascertain this is as per the aircraft - however I do notice that after releasing the stick there is a small stutter depending on airspeed. Controlling the aircraft correctly (i.e. not snap releasing) mitigates this.

[1] ROLL SAS as implemented
![image](https://user-images.githubusercontent.com/2045654/117504430-b27bd000-af82-11eb-926b-ccf56712f564.png)

**Comment by Megaf** [comment]
I tested again today on commit 7aa08a36d6bb6f5a1286922bc728e7f5fc0f5314
The jitter seems to be gone.
Only issue left is, roll doesnt return to centre in one movement, it returns around halfway, tops, and then continue returning slowly.

**Comment by Zaretto** [comment]
The maximum rate limit is 36deg/second - so from a 50 degree deflection it will take at least two seconds and probably longer because of the phase lead lag controller.

         1
---------------
   0.05 S + 1 
---------------
rate limit
36 deg/second

The 0.05 S + 1 will provide extra delay

ref:
![image](https://user-images.githubusercontent.com/2045654/118122838-b3ce5200-b3f3-11eb-9e3c-b9d276fd227e.png)

With the changes made up to and including commit f2e1dacf I now think that all of the SAS is correctly implemented

**Comment by Megaf** [comment]
I hope this video will show a few of the issues. 
https://youtu.be/W3kJr08OSSA
List of issues I tried to show here. Not in order.
1. It doesn't self centre in one movement, it centres halfway, stops, continues slowly.
2. Random roll when trying level flight without any stick input.
3. On full side deflection, the angle of spoilers oscillated, causing the roll to be not constant.
4. Rudder behaves erratically.

**Comment by Megaf** [comment]
Commit 86d17204697548d2c45411ecfba79e528b1a2cfe is absolutely beautiful.
Thank you for your great work!
Fixed by 86d17204697548d2c45411ecfba79e528b1a2cfe

**Comment by Zaretto** [comment]
@Megaf  Thanks for your persistence in testing and providing flight test reports on each set of changes.
