### ISSUE TITLE
F-14: HUD issues vs bright sky.

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#134]
Part of the HUD becomes invisible against the bright sky.
"Target" Name/Aircraft type is what becomes invisible.
![image](https://user-images.githubusercontent.com/6201512/117586469-59da3d80-b110-11eb-8d4a-359a36655df1.png)
![image](https://user-images.githubusercontent.com/6201512/117586486-665e9600-b110-11eb-9a05-4200d83f0512.png)
The real F-14 HUD part seems to have a shadow that fixes that.

**Comment by Zaretto** [comment]
This is a feature of the XML HUD and unfortunately can't be fixed. Also probably this level of identification is somewhat unrealistic.

The only way to fix this would require use of a Canvas HUD and the ALS HUD

I've decided to keep the F-14 requirements low so Canvas isn't something that I can add.

I'm closing this issue because it isn't something within current scope.
