### ISSUE TITLE
F-15: Integrate M2000 radar

### ISSUE THREAD

**Issue by Zaretto** [Zaretto/fg-aircraft#14]
Add Fabien's new radar code to the F-15.

This will require modifications to the weapons systems, probably the stores, and the HUD/MPCD.

**Comment by Raider11** [comment]
The M2000-5 radar is fantastic.  What model are you intending to model it after?  I hope that you consider the 63(V)2 AESA radar, at least 

Also, when you do make this change, are you going to manipulate any features in the TEWS?  I have been researching both the radar and TEWS extensively, and although there is still limited info on both (moreso on the TEWS), I feel like I could probably be of help in this arena, as I have spent many hours piecing together its capabilities from a number of different sources and think I have a good understanding of it post-MSIP.  Just let me know! 

Raider1

**Comment by Zaretto** [comment]
M2000 as in 5HIN0B1's radar code from FG. This is better code than the F-15 currently has.

Any information about TEWS that isn't classified will be useful. I do not want to know anything that might be classified and have no intention of trying to accurately simulate TEWS until it is declassified. 

Therefore if you have a good idea of how it works with all due respect I don't want to know. 

I intend to improve how my version of TEWS works based on what I think might be useful. Suggestions about features that might be useful in such a system can be posted here - provided they are not based on facts.

**Comment by Raider11** [comment]
Hi Richard,

Yes, I knew which radar you were referring to.  It is a great radar.  I was more referring to how you would tailor the capability of the radar to match the F15C (items such as beam width, range, etc).  My suggestion would be to model after the AN/APG-63(v)2 radar.  If you wanted specifics on this radar, I would be happy to help find open-sources that could contribute to your success without making you feel like you were crossing any lines.

Major features I would like to see is the ability to designate friendly and hostile aircraft as you flip through them on targeting. Ideally, it would be helpful if, when a target was cued, you could add a button-press to change it's symbol on the hud.  The TWS mode on the (v)2 is capable of tracking 16 aircraft via radar, and targeting up to 4, so I would say that would be a good hard limit if you wanted to look at this.  

While on the subject of radar, I was wondering if you intended to make the Situation Display functional in the MCFD when you move over the new radar.  If you were (and I hope you are considering it!) I would suggest the following:

When you migrate the 2000 code, also migrate over the canvas navigation screen and make it a option in the MFCD.  Although it uses a color or two that are not among the colors in the F15 MFCD (IIRC), it would be much better than not having it at all.  You could consider seeing how difficult it would be to overlay the data from the TEWS as well... although that might be technically challenging.

Enable the radar and the TEWS to feed into the Situation display in the MCFD.  Radar data and TEWS data should be differentiated (passive info vs active info), and it should be scaleable to the setting on the TEWS (same scales), but also could display active radar contacts.  If you take the suggestion above and make it to where a target (in the FCR, not the RWR) can be designated as hostile/civ/etc, then you could have the MCFD display a color or other indicator.

My biggest ask here is that you avoid one thing when moving over the code... please don't create a forward-looking-only display output like the one in the M2000-5.  Since the 63 and the 56 integrated data and also collect and integrate data from other aircraft and fixed radar sources, it is important to ensure that it can all be displayed in the same place in the future.  We currently have folks working on different aspects of integrating data from diverse aircraft, and it would be a shame to have the worlds most successful fighter (and arguably the most advanced avionics suite of a generation of aircraft) not able to take advantage of those advances.

As for the TEWS... I would not risk sending you anything that is not open-source.  All that I have learned about the TEWS, specifically the AN/ALR-56 RWR, has come from public sources such as press releases, published reports, congressional budgetary documents, releases from it's manufacturer (Ratheon), etc.  

At any rate, I hope you will realize I only wrote a book here because I am so passionate about this aircraft and the work you have already done.  I appreciate you even taking the time to read this, and hope you have a great day.

Raider1

**Comment by Raider11** [comment]
Richard, Leto mentioned that I was not very clear in what I meant in the paragraph "my biggest ask"...

I am not referring to the vertical radar display in the VSD, as you have it pretty close IMO.  I am referring to the Situational Display that should be in the MFCD, integrating all of the inputs in a horizontal frame.  

Also, this whole discussion got me thinking that it may be easier for you to simply leave the current radar system, but unlink it from the FCR (and subsequently the HUD and VSD), and leave it to power the TEWS only.  Then use the 2000 radar (with the parameters changed to mirror the 63 series radar of your choosing... chanting "(v)2!, (v)2!") and use it to power the HUD, VSD, and feed the SitDisp in the MFCD.  This would actually be much more realistic, as the range of the AN/ALR-56 is not limited by the current range or scan pattern of the 63... indeed the 56 functions even with the FCR turned off and would still feed the situational display.

Does that make sense or did I just get confusing?  Im confused.

Raider1

**Comment by Zaretto** [comment]
I'd always intended to make the Radar and Sensor set more accurate - so that it works more like the real thing; so one of the things that I'm looking at (before integrating Fabien's radar) is how it all works together. 

I'm not sure of the exact details until I've got more work on integration completed; but the idea is to model the current version of the airframe and avionics as accurately as I can within the constraints of FG. This may well take the path of keeping the radar and a separate sensor set which work together to produce a combined situational overview - more details as this develops.

APG-70 simulation; (lots of useful info) http://www.dtic.mil/dtic/tr/fulltext/u2/a319223.pdf

The MPCD SIT will be improved - it's been on my list for a while. 

---------------
I'm happy to receive any information about the operation of AN/ALR-56 that has non classified sources. All sources of information need to be attributable so I don't get a visit from disgruntled workers from Virginia.

**Comment by Zaretto** [comment]
Nikolai has implemented this together with the improved is terrain by terrain and many improvements to the armament simulation on both the F-14 and F-15
