### ISSUE TITLE
F-14 Roll channel slow to centre from halfway.

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#148]
Video showing the issue.
https://user-images.githubusercontent.com/6201512/124796518-29b0ee80-df49-11eb-8244-601019cb556c.mp4
![roll_slow_centre](https://user-images.githubusercontent.com/6201512/124798093-e48dbc00-df4a-11eb-94a8-48f3efacad22.gif)

As you can see, approximately from halfway its travel, the roll control surfaces will basically come to a halt and then move very slowly.

**Comment by Zaretto** [comment]
I've spent a lot of time validating that the SAS system that I've implemented is correct based on the schematics in NASA TM-81833

I will revisit this when I get some spare time and maybe I'll find something wrong.

**Comment by Zaretto** [comment]
After investigation this is being caused by the normal alpha roll augmentation logic  
![image](https://user-images.githubusercontent.com/2045654/124956874-c1c9d900-e018-11eb-80a4-7600965163a6.png)

(from https://i.imgur.com/3x7Sblj.png)

So it appears to be working as designed - i.e. it is the lead lag compensator that is causing this:

![image](https://user-images.githubusercontent.com/2045654/124957100-fdfd3980-e018-11eb-93d4-9deca986f553.png)
