### ISSUE TITLE
Blackout onset and progress.

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#150]
I believe that the pilot is blacking out too quickly in the F-14.
At 5.7 G the pilot is already almost blind, the total blackout should be at 8 G.
![image](https://user-images.githubusercontent.com/6201512/129453547-57f812e3-b93c-4a17-8645-df93a94ffba4.png)

-Edit
A well trained pilot should be able to sustain 9 Gs without G-Suit.

**Comment by Zaretto** [comment]
The readout/blackout system in the F-14 is based on the excellent work of @NikolaiVChr - which in turn builds on solid research by Gerald J. Kron and Frank M. Cardullo (Singer Link Simulation Binghampton) for the F-16.

See 

* https://forum.flightgear.org/viewtopic.php?f=4&t=30985
* https://apps.dtic.mil/dtic/tr/fulltext/u2/a109127.pdf
* https://www.skybrary.aero/index.php/G-induced_Impairment_and_the_Risk_Of_G-LOC

Other reports

* https://www.atsb.gov.au/media/761497/g-induced_loss_of_consciousness.pdf
* https://web.archive.org/web/20200325081718/https://link.springer.com/content/pdf/10.1186%2F2046-7648-2-19.pdf

So currently this is something that I consider to be working as designed, unless you can provide some concrete data to show that this isn't working as designed (e.g. comparison against F-16 or JAS-39).

**Comment by Zaretto** [comment]
Just donned my orange flightsuit and compared the F-14 and the Mirage 2000-5 and the big difference is that with the F-14 you can fairly easily pull an instantaneous 12G - which is blackout inducing (and airframe breaking). 

Flying within the envelope of the aircraft and I find that the G blackout is very similar.

This does raise an interesting point - in that the because the F-14 can pull such high G in the real world the pilots would (usually) stay under the recommended values - because otherwise trouble awaited on return; but I have no idea how we can simulate this any better than we already do with the instant blackout if you pull too much.

**Comment by Megaf** [comment]
Thanks for the reply @Zaretto, I will monitor the G levels closely on my next combat and get back here.
That said, I do believe that 8 G should not cause a lack out. Pilots do train sustaining 9 G, as shown below.
https://www.youtube.com/watch?v=o9YtD1jw_Qw

**Comment by Megaf** [comment]
Closing this as I don't have enough evidence to suggest we have an issue.

**Comment by Zaretto** [comment]
For the F-14 and F-15 I've removed the locally defined system and changed the parameters to be the same as the F-16.

I'm not sure if this changes anything - but it is the sensible thing to do.

**Comment by Megaf** [comment]
I believe it did change. Before, I'd blackout after a short time on 5G. Now I can reach 8 G without blacking out instantly.
So now it's even with the other fighters.
