### ISSUE TITLE
Camera bug with new version.

### ISSUE THREAD

**Issue by DaSovietPotato** [Zaretto/fg-aircraft#158]
In the latest version there is a bug where one of the camera views being glitched. In the glitched version the FG "Blue Hell" is visible with weird lighting and no relation to the aircraft. The aforementioned issue is also found within the F-15.

**Comment by Rudolf339** [comment]
Can you upload an image of said "FG blue hell"?

**Comment by DaSovietPotato** [comment]
![image](https://user-images.githubusercontent.com/2045654/164414412-8ab4aa21-024b-4508-a52b-928ca3fd6dee.png)

**Comment by Megaf** [comment]
> In the latest version there is a bug where one of the camera views being glitched. In the glitched version the FG "Blue Hell" is visible with weird lighting and no relation to the aircraft. The aforementioned issue is also found within the F-15.

Can you tell which of the camera views are affected?

Also, can you please tell which branch of 'fg-aircraft' repo you are in and full version of FlightGear and operating system please.

**Comment by DaSovietPotato** [comment]
The camera issue is strange as it is its own view which does not appear within the settings. For example if I disabled all of the views within FG it would remain in the Blue Hell camera.
I am currently using the FGAddon version which is 1.9.1 with FG 2020.3.13.

**Comment by Zaretto** [comment]
I have tested with the FGAddon version against 2020.3.12 and I cannot reproduce the problem. Please provide exact steps that show he problem.

**Comment by DaSovietPotato** [comment]
To better showcase the bug, I have a video of the entire process. https://www.youtube.com/watch?v=l_g-3xacr_A

**Comment by Rudolf339** [comment]
Iirc you see that when the camera gets moved to 0,0 for some reason.

**Comment by Megaf** [comment]
> To better showcase the bug, I have a video of the entire process. https://www.youtube.com/watch?v=l_g-3xacr_A

I've seen that happen before. In my case it is because I enabled a view that doesn't exist in the aircraft I'm flying.

**Comment by Zaretto** [comment]
Possibly because you have enabled the walker view in the view options. This should always be turned off.

![image](https://user-images.githubusercontent.com/2045654/164241336-d171bb92-c8e6-43d9-b6aa-469d53c6958b.png)

Please verify that your view configuration is as shown above and report back.

**Comment by DaSovietPotato** [comment]
After further testing I feel that it has something to do with the walker function, however the walker setting has no relation to the appearance of the problem. 

![image](https://user-images.githubusercontent.com/2045654/164414330-ff983a7d-503a-497a-b549-254d35e1e122.png)

**Comment by Megaf** [comment]
Did you try in a newer or older version of FG? It might be an issue in FG

**Comment by Zaretto** [comment]
@DaSovietPotato is this still a problem with the 1.12 release branch

**Comment by Megaf** [comment]
This glitch is caused by either of the walk views being enabled without walker being outside.

![image](https://user-images.githubusercontent.com/6201512/216328400-b2e385e0-62d7-41d7-b5b8-3b21201a1ab0.png)

These views don't need to be enabled in order for the walker to work.

So, I guess setting these views to false would fix this.

* `/sim/view[110]` for "Walk View".
* `/sim/view[111]` for "Walker Orbit View".

The views are already toggled when Enabling/Disabling "Waker Outside". But for some reason, by default, they are enabled and selectable on FG start up without using "Walker Outside" beforehand.

EDIT:

By the way, same apply to `/sim/view[115]` for "Ejection View", it should be set to `false` on startup along with `/sim/view[110]` and `/sim/view[111]`.

Setting them to false will prevent those cameras from being used until the views are actually available.

**Comment by Zaretto** [comment]
disabled these views which should fix this.
