### ISSUE TITLE
Cockpit veiw point of F-15

### ISSUE THREAD

**Issue by Developer0607** [Zaretto/fg-aircraft#183]
Hi there,
I found that in the F-15's cockpit, the view point seems to be inside the seat. Shall we put it a little forward?

**Comment by Zaretto** [comment]
The only issue I can see is that as you turn around the seat gets Zclipped. This can probably be fixed by adjustments to the view parameters.

Getting the eyepoint correct isn't as easy as it seems. I spent a fair amount of time doing this originally and unless you can provide evidence that the eyepoint is wrong it will remain where it is.
