### ISSUE TITLE
Elevator doesn't appear to function on f-14 variants (a, b, etc).

### ISSUE THREAD

**Issue by asydney** [Zaretto/fg-aircraft#89]
Hi Zaretto,
                I'm not sure if there is a bug/not since I'm new to flightgear, but to summarize, though I can see the stick visually move when I use use the up/down key on my keyboard, the aircraft doesn't seem to respond. Here are the details:

* I'm running flightgear 2019.1.1
* From your website I'm running flightgear model 1.8.1 (i.e. I've pulled it from your github repo)
* My OS is Ubuntu 16.04
* When I start, say the f-14b, I go to "Tomcat Controls -> Fuel and stores" and select max values on all tanks.
* I then do "Tomcat Controls -> Quickstart"
* Check that the wings are set to "auto" sweep.
* Disengage parking brake.
* Use "page up" on the keyboard to take off. At this point, the aircraft accelerates but pressing
down/2 on the keyboard doesn't result in any change.

Notes:
1. Pressing 0 or "Enter" doesn't affect the rudder.
2. Using "f/F" from the keyboard has no effect on the flaps.
3. I've looked at a few videos on taking off (ex. https://www.youtube.com/watch?v=PirnWJHZtcg) and it appears that the "NWS ENGA" option is selected near the HUD interface of the front seat. However, mine is disabled.

Thoughts?

**Comment by Zaretto** [comment]
The files on my website are now out of date; what you should do is to remove this model and then install the F-14 from the Launcher using the default hangar and selecting the Browser button.

![image](https://user-images.githubusercontent.com/2045654/70790725-f373b300-1d95-11ea-9220-c63431fe772a.png)

I will update my website soon to indicate that the F-14 now comes with FlightGear. Thanks for the report.

If installing the latest version fixes the problem then please close this issue otherwise report what the problems are and I will try to help.

**Comment by asydney** [comment]
Installing the aircrafts from the launcher works perfectly! Not sure why I didn't come across this method of installing aircrafts in the first place.

Thanks a bunch!
